version: '3.8'
services:
  mongodb:
    image: mongo:latest

    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3333:3333
    command: npm run start:dev
    
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: